from __future__ import annotations

from dataclasses import dataclass
from datetime import date, timedelta
from typing import Literal, Sequence

ScaleKind = Literal[
    "day",
    "week",
    "month",
    "quarter",
    "year",
    "fiscal_year",
    "fiscal_quarter",
    "fixed_days",
    "countdown",
]


@dataclass(frozen=True)
class ScaleSpec:
    """Describes one stacked timescale row."""

    name: str
    kind: ScaleKind
    anchor: date | None = None
    length_days: int | None = None
    week_start: int = 0  # Monday=0 .. Sunday=6
    fiscal_year_start: tuple[int, int] = (1, 1)  # (month, day)
    day_label_format: str = "%Y-%m-%d"
    countdown_to: date | None = None
    countdown_prefix: str = "D"
    countdown_zero_label: str = "D-Day"


@dataclass(frozen=True)
class PeriodSpan:
    """One contiguous period in a timescale row."""

    label: str
    start: date
    end: date
    start_idx: int
    end_idx: int


@dataclass(frozen=True)
class TimescaleRow:
    """One named row in a stacked timeline."""

    name: str
    spans: tuple[PeriodSpan, ...]


@dataclass(frozen=True)
class TimescaleResult:
    """Complete aligned timescales for a date range."""

    start: date
    end: date
    columns: tuple[date, ...]  # daily columns in range [start, end]
    rows: tuple[TimescaleRow, ...]


def generate_timescales(
    start: date,
    end: date,
    scales: Sequence[ScaleSpec],
) -> TimescaleResult:
    """Generate stacked, day-aligned timescales across a date range.

    Each row is generated by grouping daily columns into contiguous spans that share
    the same period key for that row's `ScaleSpec`.
    """
    if start > end:
        raise ValueError("start must be <= end")

    days = tuple(start + timedelta(days=i) for i in range((end - start).days + 1))
    rows = tuple(_build_row(days, spec) for spec in scales)
    return TimescaleResult(start=start, end=end, columns=days, rows=rows)


def _build_row(days: Sequence[date], spec: ScaleSpec) -> TimescaleRow:
    spans: list[PeriodSpan] = []

    current_label = None
    current_start_idx = 0

    for idx, d in enumerate(days):
        label = _label_for_day(d, spec)
        if current_label is None:
            current_label = label
            current_start_idx = idx
            continue
        if label != current_label:
            spans.append(
                PeriodSpan(
                    label=current_label,
                    start=days[current_start_idx],
                    end=days[idx - 1],
                    start_idx=current_start_idx,
                    end_idx=idx - 1,
                )
            )
            current_label = label
            current_start_idx = idx

    spans.append(
        PeriodSpan(
            label=current_label or "",
            start=days[current_start_idx],
            end=days[-1],
            start_idx=current_start_idx,
            end_idx=len(days) - 1,
        )
    )
    return TimescaleRow(name=spec.name, spans=tuple(spans))


def _label_for_day(d: date, spec: ScaleSpec) -> str:
    if spec.kind == "day":
        return d.strftime(spec.day_label_format)
    if spec.kind == "week":
        week_start = d - timedelta(days=(d.weekday() - spec.week_start) % 7)
        return f"Week of {week_start:%Y-%m-%d}"
    if spec.kind == "month":
        return d.strftime("%b %Y")
    if spec.kind == "quarter":
        q = ((d.month - 1) // 3) + 1
        return f"Q{q} {d.year}"
    if spec.kind == "year":
        return str(d.year)
    if spec.kind == "fiscal_year":
        fy = _fiscal_year_number(d, spec.fiscal_year_start)
        return f"FY{fy}"
    if spec.kind == "fiscal_quarter":
        q, fy = _fiscal_quarter_and_year(d, spec.fiscal_year_start)
        return f"FQ{q} FY{fy}"
    if spec.kind == "fixed_days":
        if not spec.anchor or not spec.length_days or spec.length_days <= 0:
            raise ValueError(
                f"Scale '{spec.name}' with kind=fixed_days requires anchor and positive length_days"
            )
        n = _fixed_period_index(d, spec.anchor, spec.length_days)
        return f"{spec.name} {n}"
    if spec.kind == "countdown":
        if not spec.countdown_to:
            raise ValueError(
                f"Scale '{spec.name}' with kind=countdown requires countdown_to"
            )
        delta = (spec.countdown_to - d).days
        if delta > 0:
            return f"{spec.countdown_prefix}-{delta}"
        if delta < 0:
            return f"{spec.countdown_prefix}+{-delta}"
        return spec.countdown_zero_label
    raise ValueError(f"Unsupported kind: {spec.kind}")


def _fiscal_year_number(d: date, fiscal_start: tuple[int, int]) -> int:
    start = _fiscal_year_start_for_date(d, fiscal_start)
    # FY is named by the year in which the fiscal period ends.
    return (_add_months(start, 12) - timedelta(days=1)).year


def _fiscal_quarter_and_year(d: date, fiscal_start: tuple[int, int]) -> tuple[int, int]:
    fy_start = _fiscal_year_start_for_date(d, fiscal_start)
    q2 = _add_months(fy_start, 3)
    q3 = _add_months(fy_start, 6)
    q4 = _add_months(fy_start, 9)

    if d < q2:
        quarter = 1
    elif d < q3:
        quarter = 2
    elif d < q4:
        quarter = 3
    else:
        quarter = 4

    fy = (_add_months(fy_start, 12) - timedelta(days=1)).year
    return quarter, fy


def _fiscal_year_start_for_date(d: date, fiscal_start: tuple[int, int]) -> date:
    month, day = fiscal_start
    candidate = _safe_date(d.year, month, day)
    if d >= candidate:
        return candidate
    return _safe_date(d.year - 1, month, day)


def _fixed_period_index(d: date, anchor: date, length_days: int) -> int:
    delta_days = (d - anchor).days
    return (delta_days // length_days) + 1


def _add_months(d: date, months: int) -> date:
    month_zero = (d.month - 1) + months
    year = d.year + month_zero // 12
    month = (month_zero % 12) + 1
    day = min(d.day, _days_in_month(year, month))
    return date(year, month, day)


def _safe_date(year: int, month: int, day: int) -> date:
    return date(year, month, min(day, _days_in_month(year, month)))


def _days_in_month(year: int, month: int) -> int:
    if month == 12:
        next_month = date(year + 1, 1, 1)
    else:
        next_month = date(year, month + 1, 1)
    return (next_month - date(year, month, 1)).days


if __name__ == "__main__":
    # Example matching the stacked idea in Blockplan.xlsx.
    cfg = [
        ScaleSpec("Fiscal Year", "fiscal_year", fiscal_year_start=(1, 1)),
        ScaleSpec("Fiscal Quarter", "fiscal_quarter", fiscal_year_start=(1, 1)),
        ScaleSpec("PI", "fixed_days", anchor=date(2024, 1, 1), length_days=91),
        ScaleSpec("Sprint", "fixed_days", anchor=date(2024, 1, 1), length_days=14),
        ScaleSpec("Month", "month"),
        ScaleSpec("Launch Countdown", "countdown", countdown_to=date(2024, 2, 15)),
        ScaleSpec("Date", "day", day_label_format="%d"),
        ScaleSpec("DoW", "day", day_label_format="%a"),
    ]

    result = generate_timescales(date(2024, 1, 1), date(2024, 3, 31), cfg)
    for row in result.rows:
        print(row.name)
        print("  ", [f"{s.label}[{s.start_idx}:{s.end_idx}]" for s in row.spans[:6]], "...")
