"""docs/DefaultRendererValues.md must describe the renderers as they are.

The document is generated by measuring what each view draws with when the
theme sets nothing, so a renderer that gains, loses or changes a fallback
silently invalidates it.  It had in fact drifted across several commits:
`ec-label`/`opacity` and every `base.default_missing_icon_color` row were
missing, among ~80 others.

Sources are cited as `file.py:function`, not by line number, so moving code
around leaves the document alone and it can be compared exactly: a failure
here always means a key, a default or a call site really changed.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from tools.generate_default_renderer_values import build_document  # noqa: E402

DOC = REPO_ROOT / "docs" / "DefaultRendererValues.md"


def _rows(text: str) -> list[str]:
    return [ln for ln in text.splitlines() if ln.startswith("| ") and not ln.startswith("|---")]


def test_the_document_matches_the_renderers():
    """Regenerate with: uv run python tools/generate_default_renderer_values.py"""
    committed = DOC.read_text()
    current = build_document()
    assert committed == current


def test_no_documented_row_has_disappeared():
    """A clearer failure than the whole-document diff when rows go missing."""
    committed = set(_rows(DOC.read_text()))
    current = set(_rows(build_document()))
    missing = sorted(current - committed)
    assert missing == [], f"{len(missing)} rows the renderers have but the document lacks: {missing[:5]}"


def test_no_stale_row_survives():
    committed = set(_rows(DOC.read_text()))
    current = set(_rows(build_document()))
    stale = sorted(committed - current)
    assert stale == [], f"{len(stale)} rows the document still claims: {stale[:5]}"


def test_every_row_has_a_default():
    """An empty default cell means the generator failed to evaluate a chain."""
    empty = [r for r in _rows(DOC.read_text()) if re.search(r"\|\s*\|", r)]
    assert empty == [], f"{len(empty)} rows with an empty cell: {empty[:3]}"


def test_the_pattern_scale_settings_are_documented():
    """The settings whose absence prompted this guard."""
    text = DOC.read_text()
    for key in (
        "weekly.day_box.hash_pattern_target_size",
        "weekly.day_box.hash_pattern_scale",
        "weekly.day_box.hash_pattern_opacity",
    ):
        assert f"`{key}`" in text, key
