BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "events" (
	"id"	INTEGER NOT NULL,
	"user_id"	INTEGER NOT NULL,
	"import_id"	INTEGER NOT NULL,
	"status"	TEXT,
	"priority"	NUMERIC,
	"wbs"	TEXT,
	"rollup"	INTEGER,
	"milestone"	INTEGER,
	"percent_complete"	REAL,
	"name"	TEXT,
	"effort"	REAL,
	"duration"	REAL,
	"start_date"	TEXT,
	"end_date"	TEXT,
	"earliest_start_date"	TEXT,
	"latest_start_date"	TEXT,
	"earliest_end_date"	TEXT,
	"latest_end_date"	TEXT,
	"predecessors"	TEXT,
	"resource_names"	TEXT,
	"resource_group"	TEXT,
	"notes"	TEXT,
	"icon"	TEXT,
	"color"	TEXT,
	"tags"	TEXT,
	"source_id"	TEXT,
	"critical"	INTEGER,
	"start_time"	TEXT,
	"end_time"	TEXT,
	"duration_text"	TEXT,
	"effort_text"	TEXT,
	"actual_start_date"	TEXT,
	"actual_start_time"	TEXT,
	"actual_end_date"	TEXT,
	"actual_end_time"	TEXT,
	"deadline"	TEXT,
	"start_variance"	TEXT,
	"finish_variance"	TEXT,
	"fixed_cost"	REAL,
	"cost"	REAL,
	"percent_work_complete"	REAL,
	"successors"	TEXT,
	"custom1"	TEXT,
	"custom2"	TEXT,
	"custom3"	TEXT,
	"custom4"	TEXT,
	"custom5"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE INDEX IF NOT EXISTS "date" ON "events" (
	"start_date"	ASC
);
COMMIT;
